package com.defecttracker.dto.response;

import java.time.LocalDateTime;

public record TestCaseSummary(
    Long id,
    String testcaseNo,
    String description,
    String detailsSteps,
    String expectedResult,
    SubModuleSummary subModule,
    SeveritySummary severity,
    DefectTypeSummary defectType,
    String type,
    Boolean testCaseRequired,
    String executionStatus,
    EmployeeResponse assignedQa,
    String createdBy,
    String updatedBy,
    LocalDateTime createdAt,
    LocalDateTime updatedAt,
    String moduleName,
    Long projectId,
    Long subModuleId,
    Long defectTypeId,
    Long moduleId,
    Long severityId,
    String severityName,
    String subModuleName,
    String steps,
    String no,
    String defectTypeName
) {
    public TestCaseSummary(
        Long id,
        String testcaseNo,
        String description,
        String detailsSteps,
        String expectedResult,
        SubModuleSummary subModule,
        SeveritySummary severity,
        DefectTypeSummary defectType,
        String type,
        Boolean testCaseRequired,
        String executionStatus,
        EmployeeResponse assignedQa,
        String createdBy,
        String updatedBy,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        String moduleName,
        Long projectId
    ) {
        this(
            id,
            testcaseNo,
            description,
            detailsSteps,
            expectedResult,
            subModule,
            severity,
            defectType,
            type,
            testCaseRequired,
            executionStatus,
            assignedQa,
            createdBy,
            updatedBy,
            createdAt,
            updatedAt,
            moduleName,
            projectId,
            subModule != null ? subModule.id() : null,
            defectType != null ? defectType.id() : null,
            subModule != null ? subModule.moduleId() : null,
            severity != null ? severity.id() : null,
            severity != null ? severity.name() : null,
            subModule != null ? subModule.name() : null,
            detailsSteps,
            testcaseNo,
            defectType != null ? defectType.name() : null
        );
    }
}
